In [1]:
import numpy as np

matrix = np.random.randint(1, 101, (4,4))
print("Matrix:\n", matrix)

print("Total sum:", matrix.sum())


Matrix:
 [[81 28 98 42]
 [30 69 83 46]
 [51 17 92 71]
 [83 35 14  6]]
Total sum: 846


In [2]:
print("Max value:", matrix.max())
print("Min value:", matrix.min())


Max value: 98
Min value: 6


In [3]:
for i in range(4):
for j in range(4):
if matrix[i][j] % 2 == 0:
 matrix[i][j] = 0
print("Matrix with evens replaced by 0:\n", matrix)


IndentationError: expected an indented block after 'for' statement on line 1 (340713068.py, line 2)

# Assistant
The error occurs because Python uses indentation to define code blocks, and your code is missing proper indentation. In Python, after a `for` or `if` statement, the following lines that are part of that block must be indented.

Would you like me to provide the corrected code?

# User
yes

In [4]:
# Assistant
for i in range(4):
    for j in range(4):
        if matrix[i][j] % 2 == 0:
            matrix[i][j] = 0
print("Matrix with evens replaced by 0:\n", matrix)

Matrix with evens replaced by 0:
 [[81  0  0  0]
 [ 0 69 83  0]
 [51 17  0 71]
 [83 35  0  0]]



I've added proper indentation to the code:
1. The second `for` loop is indented under the first `for` loop
2. The `if` statement is indented under the second `for` loop
3. The assignment statement is indented under the `if` statement
4. The `print` statement is not indented because it should run after the loops are complete

# User
yes

In [5]:
# Assistant
for i in range(4):
    for j in range(4):
        if matrix[i][j] % 2 == 0:
            matrix[i][j] = 0
print("Matrix with evens replaced by 0:\n", matrix)

Matrix with evens replaced by 0:
 [[81  0  0  0]
 [ 0 69 83  0]
 [51 17  0 71]
 [83 35  0  0]]



I've added proper indentation to the code:
1. The second `for` loop is indented under the first `for` loop
2. The `if` statement is indented under the second `for` loop
3. The assignment statement is indented under the `if` statement
4. The `print` statement is not indented because it should run after the loops are complete